# Generated by Django 4.1.3 on 2022-12-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='numero_pasaporte',
            new_name='numero_documento',
        ),
    ]
