# Generated by Django 4.1.3 on 2022-12-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_rename_numero_pasaporte_familiar_numero_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='numero_documento',
            new_name='numero_pasaporte',
        ),
    ]
