# Generated by Django 4.1.3 on 2022-12-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_rename_numero_documento_familiar_numero_pasaporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
