# Generated by Django 4.1.3 on 2022-12-08 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_remove_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 1, 10, 33, 417533, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
