# Generated by Django 4.1.3 on 2022-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0006_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name=['%m-%d-%Y']),
        ),
    ]
