# Generated by Django 4.1.3 on 2022-12-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0008_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('cantidad_de_puertas', models.IntegerField()),
                ('fecha_patentamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('fecha_adopcion', models.DateField()),
            ],
        ),
    ]
